import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '../components/ui/sidebar'
import { AppSidebar } from '../components/app-sidebar'
import Footer from '../components/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <SidebarProvider>
        <AppSidebar />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main className='w-full h-full'>
            <SidebarTrigger />
            {children}
          </main>
        </body>
      </SidebarProvider>
      <Footer />
    </html>
  )
}
